/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.GameViewController;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Camilo
 */
public class GameView extends MyFrame{

    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
        GameViewController.load(this);
    }
    
    public GameView(JFrame father) {
        initComponents();
        this.setFather(father);
        GameViewController.load(this);
    }

    public JLabel getjLLastCard() {
        return jLLastCard;
    }

    public void setjLLastCard(JLabel jLLastCard) {
        this.jLLastCard = jLLastCard;
    }

    public JLabel getjLLocalInfo() {
        return jLLocalInfo;
    }

    public void setjLLocalInfo(JLabel jLLocalInfo) {
        this.jLLocalInfo = jLLocalInfo;
    }

    public JLabel getjLPlayers() {
        return jLPlayers;
    }

    public void setjLPlayers(JLabel jLPlayers) {
        this.jLPlayers = jLPlayers;
    }

    public JPanel getjPColor() {
        return jPColor;
    }

    public void setjPColor(JPanel jPColor) {
        this.jPColor = jPColor;
    }

    public JScrollPane getjSPLocalHand() {
        return jSPLocalHand;
    }

    public void setjSPLocalHand(JScrollPane jSPLocalHand) {
        this.jSPLocalHand = jSPLocalHand;
    }

    public JPanel getjPDecks() {
        return jPDecks;
    }

    public void setjPDecks(JPanel jPDecks) {
        this.jPDecks = jPDecks;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTablero = new javax.swing.JPanel();
        jSPLocalHand = new javax.swing.JScrollPane();
        jPCenter = new javax.swing.JPanel();
        jPDecks = new javax.swing.JPanel();
        jPColor = new javax.swing.JPanel();
        jLPlayers = new javax.swing.JLabel();
        jLLocalInfo = new javax.swing.JLabel();
        jLLastCard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPTablero.setBackground(new java.awt.Color(102, 102, 102));
        jPTablero.setPreferredSize(new java.awt.Dimension(200, 150));
        jPTablero.setLayout(new java.awt.BorderLayout());

        jSPLocalHand.setBackground(new java.awt.Color(255, 255, 51));
        jSPLocalHand.setOpaque(false);
        jSPLocalHand.setPreferredSize(new java.awt.Dimension(2, 150));
        jPTablero.add(jSPLocalHand, java.awt.BorderLayout.SOUTH);

        jPCenter.setBackground(new java.awt.Color(0, 153, 153));
        jPCenter.setPreferredSize(new java.awt.Dimension(640, 480));

        jPDecks.setOpaque(false);

        jPColor.setOpaque(false);
        jPColor.setPreferredSize(new java.awt.Dimension(120, 75));

        javax.swing.GroupLayout jPColorLayout = new javax.swing.GroupLayout(jPColor);
        jPColor.setLayout(jPColorLayout);
        jPColorLayout.setHorizontalGroup(
            jPColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPColorLayout.setVerticalGroup(
            jPColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jLPlayers.setText("Cartas:");
        jLPlayers.setMinimumSize(new java.awt.Dimension(100, 14));

        jLLocalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLocalInfo.setText("Turno");
        jLLocalInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLLastCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLastCard.setText("Carta deee");
        jLLastCard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPCenterLayout = new javax.swing.GroupLayout(jPCenter);
        jPCenter.setLayout(jPCenterLayout);
        jPCenterLayout.setHorizontalGroup(
            jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCenterLayout.createSequentialGroup()
                        .addComponent(jLPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addComponent(jPColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCenterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLLastCard)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLLocalInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPCenterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPDecks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPCenterLayout.setVerticalGroup(
            jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(jLLastCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLLocalInfo)
                .addContainerGap())
            .addGroup(jPCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPCenterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPDecks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPTablero.add(jPCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPTablero, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GameView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLLastCard;
    private javax.swing.JLabel jLLocalInfo;
    private javax.swing.JLabel jLPlayers;
    private javax.swing.JPanel jPCenter;
    private javax.swing.JPanel jPColor;
    private javax.swing.JPanel jPDecks;
    private javax.swing.JPanel jPTablero;
    private javax.swing.JScrollPane jSPLocalHand;
    // End of variables declaration//GEN-END:variables
}
