/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.MainViewController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 * Clase de la ventana inicial de la aplicacion
 * @author Camilo
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        MainViewController.load(this);
    }

    public JLabel getjLTurn() {
        return jLTurn;
    }

    public void setjLTurn(JLabel jLTurn) {
        this.jLTurn = jLTurn;
    }

    public JLabel getjLPlayer() {
        return jLPlayer;
    }

    public void setjLPlayer(JLabel jLPlayer) {
        this.jLPlayer = jLPlayer;
    }

    public JLabel getjLCards() {
        return jLCards;
    }

    public void setjLCards(JLabel jLCards) {
        this.jLCards = jLCards;
    }

    public JTextField getjTFPort() {
        return jTFPort;
    }

    public void setjTFPort(JTextField jTFPort) {
        this.jTFPort = jTFPort;
    }

    public JButton getjBGameStart() {
        return jBGameStart;
    }

    public void setjBGameStart(JButton jBGameStart) {
        this.jBGameStart = jBGameStart;
    }

    public JButton getjBPortStart() {
        return jBPortStart;
    }

    public void setjBPortStart(JButton jBPortStart) {
        this.jBPortStart = jBPortStart;
    }

    public JButton getjBPortStop() {
        return jBPortStop;
    }

    public void setjBPortStop(JButton jBPortStop) {
        this.jBPortStop = jBPortStop;
    }

    public JLabel getjLInfo() {
        return jLInfo;
    }

    public void setjLInfo(JLabel jLInfo) {
        this.jLInfo = jLInfo;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLPuerto = new javax.swing.JLabel();
        jTFPort = new javax.swing.JTextField();
        jBPortStart = new javax.swing.JButton();
        jBPortStop = new javax.swing.JButton();
        jLInfo = new javax.swing.JLabel();
        jLCards = new javax.swing.JLabel();
        jLPlayer = new javax.swing.JLabel();
        jLTurn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBGameStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLPuerto.setText("Puerto:");

        jTFPort.setPreferredSize(new java.awt.Dimension(60, 20));

        jBPortStart.setText("Start");
        jBPortStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPortStartActionPerformed(evt);
            }
        });

        jBPortStop.setText("Stop");
        jBPortStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPortStopActionPerformed(evt);
            }
        });

        jLInfo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLInfo.setPreferredSize(new java.awt.Dimension(200, 30));

        jLCards.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLCards.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCards.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCards.setPreferredSize(new java.awt.Dimension(300, 30));

        jLPlayer.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPlayer.setPreferredSize(new java.awt.Dimension(100, 25));

        jLTurn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTurn.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBPortStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLPuerto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBPortStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPuerto)
                    .addComponent(jLPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPortStart)
                    .addComponent(jLTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPortStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jBGameStart.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jBGameStart.setText("START GAME");
        jBGameStart.setPreferredSize(new java.awt.Dimension(150, 35));
        jBGameStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGameStartActionPerformed(evt);
            }
        });
        jPanel2.add(jBGameStart);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPortStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPortStartActionPerformed
        MainViewController.startComm();
    }//GEN-LAST:event_jBPortStartActionPerformed

    private void jBPortStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPortStopActionPerformed
        MainViewController.stopComm();
    }//GEN-LAST:event_jBPortStopActionPerformed

    private void jBGameStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGameStartActionPerformed
        MainViewController.startGame();
    }//GEN-LAST:event_jBGameStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGameStart;
    private javax.swing.JButton jBPortStart;
    private javax.swing.JButton jBPortStop;
    private javax.swing.JLabel jLCards;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JLabel jLPlayer;
    private javax.swing.JLabel jLPuerto;
    private javax.swing.JLabel jLTurn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFPort;
    // End of variables declaration//GEN-END:variables
}
